Dev/upgrade crate and driver
Zoomdata/edc-cratedb pull request #14
Opened 2017-01-03 21:37 UTC by bowenwr

There was an existing branch and PR for this, but to make the integration tests work, some more extensive work was needed even after the core framework was updated.

This Crate connector passes all integration tests and still connects to Zoomdata. Partitioned flags are treated as `PLAYABLE`.

Ruslan - your feedback is welcome if you have any. Thanks!

2017-01-03 21:51 UTC, antinodes approved these changes

2017-01-07 15:26 UTC, kovrus requested changes

2017-01-07 15:26 UTC, kovrus commented on src/main/java/com/zoomdata/connector/example/provider/cratedb/CrateDBMetaFlagsDetector.java
> +                .map(String::toLowerCase)
If the column name is a quoted identifier, then it must be treated as a case-sensitive string. For all other cases, it is fine to lowercase column names. Therefore, we probably should not lowercase all column names.
```
"Foo" -> Foo
Foo -> foo
```
https://crate.io/docs/reference/sql/reference/lexical_structure.html

2017-01-07 15:26 UTC, kovrus commented on README.md
> +`datasource add -n cratedb CONNECTOR_TYPE CRATEDB JDBC_URL crate://localhost:5432`
`crate://localhost:5432` -> `crate://localhost:5432/`

2017-01-07 17:14 UTC, merged